name: 'Asana Tasks Action'
description: 'Mark Asana task as completed when PR gets merged'
inputs:
  asana_token:
    description: 'Asana Token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
